### ISSUE TITLE
Tracking Proposals

### ISSUE THREAD

**Issue by jamiebuilds** [shapesecurity/shift-spec#119]
Hi, I talked to @bakkot a bit about this but I wanted to create a more open issue about it.

Shift is really great to work with, but it's limited to completed ECMAScript specs. I was wondering if people would be up for a bit more formality around proposals.

I'm not looking for a bunch of unstable things to be added to the spec, just that there's a place for in progress specs to agree "If the spec is accepted in its current form, this is what the Shift AST would look like" and the acknowledgement that it could change.

A lot of it is obvious, like `catch (e) {}` &rarr; `catch {}`, but stuff [like class properties is not](https://github.com/shapesecurity/shift-spec/blob/es2017/spec.idl#L225).

It would also be really nice if there was a document for all of these and you didn't have to go through all the issues.

**Comment by michaelficarra** [comment]
:+1: It's never too early to say "if the feature makes it to stage 4 as-is, what would it look like in the Shift spec?". These could even be tracked as PRs.

**Comment by jamiebuilds** [comment]
Here's the current list of syntax proposals, would you like me to start working my way through them and open up PRs proposing AST changes for them?

- [x] Rest/Spread Properties (Stage 3) - #121
- [x] Asynchronous Iteration (Stage 3) - #122
- [x] Dynamic Import (Stage 3) - #123
- [x] ~~RegExp Unicode Property Escapes (Stage 3)~~ (No AST changes needed)
- [x] ~~RegExp Named Capture Groups (Stage 3)~~ (No AST changes needed)
- [x] RegExp DotAll Flag (Stage 3) #124
- [ ] Class Fields (Stage 3)
- [x] function.sent (Stage 2) #125
- [ ] Class and Property Decorators (Stage 2)
- [x] BigInt (Stage 2) #127
- [x] import.meta (Stage 2) #126
- [x] export * as ns from "mod"; (Stage 1) #129
- [x] export v from "mod"; (Stage 1) #128
- [x] ~~Generator Arrow Functions (Stage 1)~~ (Already described by `Function`)
- [x] Optional Chaining (Stage 1) #130
- [x] do Expressions (Stage 1) #131
- [x] ~~Numeric Separator (Stage 1)~~ (No AST changes needed)
- [x] Function Bind (Stage 0) #132
- [ ] Pattern matching (Stage 0)

**Comment by jamiebuilds** [comment]
In order to support class fields, could I change [`ClassElement.method`](https://github.com/shapesecurity/shift-spec/blob/5ec1b2d48b3d2458b9d1aa435933c1ce6cc549c3/spec.idl#L225) to something like `element` or `value`?

**Comment by michaelficarra** [comment]
FYI, I probably won't be spending any time reviewing the stage 1 and earlier proposals since they're so likely to change in some way. But thanks for sending over the PRs.
